### ISSUE TITLE
Adding Functionality to Enter Your API Key section

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#23]
**Is your feature request related to a problem? Please describe.**
- When the user puts his/her API Key in the `Enter Your API Key` section, the image should be generated.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/92e4dc29-2133-47b8-83e3-79f9ad0ec712)

**Comment by mani200307** [comment]
Can I work on this issue? Could you please assign me this?

**Comment by SurajPratap10** [comment]
Sure!! assigning it to you @mani200307 📌

**Comment by Shounmay** [comment]
<h3> I have worked on a project with OpenAI APIs integration and have understood he problem that has occured in this issue</h3>

<h1>Solution Approach</h1>
<h2> Here After taking the input of API Key from Client side, we have to update it .env file and then after we can get connected to OPENAPI server and start working. We have to update it in the controller function. For that we have to change the structure of the function and the arguments, so that we get the API_KEY from client side which we are not passing as argument. </h2> 

<h3> Can you assign it to me, as I can use my previous experience here to implement this feature in an efficient way  </h3>

**Comment by Shounmay** [comment]
@SurajPratap10 Can you assign it to me , So that i can raise a PR for it.

**Comment by SurajPratap10** [comment]
@mani200307 is working on it , so you both can collaborate and work on this as this is a `Major` update so assigning it to you too @Shounmay
