### ISSUE TITLE
Make the THEME TOGGLER sticky

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#292]
**Describe the bug**
- On scrolling down/up the `theme toggler` also moves with the screen 
- Just make it `stick` to the top

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/6cf0fc7f-a365-4dac-a1cb-e511d4b051ee)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AishwaryaSatpute1** [comment]
Title: Bug: Theme Toggler Moves with Scrolling Instead of Sticking to the Top

Description:
Currently, the theme toggler on our web page is not behaving as expected. When scrolling down or up, the theme toggler also moves along with the screen instead of remaining fixed at the top. This behavior is not consistent with the desired functionality, and it needs to be addressed.

To Reproduce:

    Go to the webpage where the theme toggler is located.
    Click on any element or perform any action that triggers scrolling.
    Scroll down or up on the page.
    Observe that the theme toggler also moves with the scrolling instead of remaining fixed at the top.

Expected Behavior:
The theme toggler should remain fixed at the top of the page regardless of the scrolling action performed by the user. It should not move or change its position relative to the viewport.

Please assign me this bug, and I'll work on fixing the issue by ensuring that the theme toggler remains fixed at the top as expected.

**Comment by SurajPratap10** [comment]
Assigned @AishwaryaSatpute1
